[package]
name = "sled-orm"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
sled = "0.34.7"

[dev-dependencies]
tempfile = "3.3"
